package application.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.sql.SQLException;

import javax.swing.JOptionPane;

import application.model.Professor;
import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

public class PrincipalController {
	@FXML
	private TextField tfCodigoProfessor;
	@FXML
	private TextField tfNomeProfesor;
	@FXML
	private TextField tfTitulacaoProfessor;
	@FXML
	private Button btnBuscarProfessor;
	@FXML
	private Button btnInserirProfessor;
	@FXML
	private Button btnAtualizarProfessor;
	@FXML
	private Button btnExcluirProfessor;
	@FXML
	private Button btnListarProfessor;
	@FXML
	private TextArea taListaProfessores;
	@FXML
	private Button btnCopiaProfessor;
	@FXML
	private TextField tfCodigoDisciplina;
	@FXML
	private TextField tfNomeDiscilplina;
	@FXML
	private TextField tfCodigoProfessorDisciplina;
	@FXML
	private Button btnBuscarDisciplina;
	@FXML
	private Button btnInserirDisciplina;
	@FXML
	private Button btnAtualizarDisciplina;
	@FXML
	private Button btnExcluirDisciplina;
	@FXML
	private Button btnListarDisciplina;
	@FXML
	private TextArea taListaDisciplinaes;

	@FXML
	public void acaoProfessor(ActionEvent event) {
		String cmd = event.getSource().toString();
		System.out.println(cmd);
		
		ProfessorController professorController = new ProfessorController
				(tfCodigoProfessor, tfNomeProfesor, tfTitulacaoProfessor, taListaProfessores);
		
		if ((cmd.contains("Inserir") || cmd.contains("Atualizar"))
				&& (tfCodigoProfessor.getText().isEmpty() || tfNomeProfesor.getText().isEmpty() 
				|| tfTitulacaoProfessor.getText().isEmpty())) 
		{
		
			JOptionPane.showMessageDialog(null, "Preencha os campos", "ERRO", JOptionPane.ERROR_MESSAGE);
			
		} else {
			if ((cmd.contains("Excluir") || cmd.contains("Buscar") || cmd.contains("tfCodigoProfessor")) 
					&& tfCodigoProfessor.getText().isEmpty()) 
			{
				JOptionPane.showMessageDialog(null, "Preencha o código", "ERRO", JOptionPane.ERROR_MESSAGE);
			} else {
				try {
					if (cmd.contains("Listar")) {
						professorController.buscarProfessores();
					} else {
						Professor p = new Professor();
						p.setCodigo(Integer.parseInt(tfCodigoProfessor.getText()));
						p.setNome(tfNomeProfesor.getText());
						p.setTitulacao(tfTitulacaoProfessor.getText());
						if (cmd.contains("Inserir")) {
							professorController.inserirProfessor(p);
						} else if (cmd.contains("Atualizar")) {
							professorController.atualizarProfessor(p);
						} else if (cmd.contains("Excluir")) {
							professorController.excluirProfessor(p);
						} else if (cmd.contains("Buscar") || cmd.contains("tfCodigoProfessor")) {
							professorController.bucarProfessor(p);
						}
					}
				} catch (ClassNotFoundException | SQLException e) {
					JOptionPane.showMessageDialog(null, e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
					e.printStackTrace();
				}
			}
		}
	
	
	}
	

	// Event Listener on Button[#btnCopiaProfessor].onAction
	@FXML
	public void copiaProfessor(ActionEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on TextField[#tfCodigoDisciplina].onAction
	@FXML
	public void acaoDisciplina(ActionEvent event) {
		// TODO Autogenerated
	}
}